
emoji_docs = {
    'happy, joy, relaxed, content': ['😀', '🥰'], 
    'funny, joke': ['😆', '🤣'], 
    'love': ['😍'], 
    'world, travel, international': ['🌎'], 
    'party, gathering, fun': ['🎉'], 
    'hungry, yummy, delicious': ['😋'], 
    'cool, hip': ['😎'], 
    'sad, worried': ['😟'], 
    'surprised, mind-blowing': ['🤯'], 
    'sleepy, sleeping, tired': ['😴'], 
    'smart, intelligence, knowledge': '🧠', 
    'dork, nerdy': ['🤓'], 
    'weird, alien, strange': ['👾'], 
    'toilet, poop': ['🚽', '💩'], 
    'impressive, amazing, congratulations': ['👏🏻'], 
    'okay, understood, got it': ['👌'], 
    'running, exercise': ['🏃‍♀️', '🏋️'], 
    'dog, dogs': ['🐶'],
    'fish': ['🐠'], 
    'ocean, sea, river, lake': ['🌊'], 
    'bicycle, biking': ['🚴'], 
    'nature, trees': ['🌴'], 
    'desert': ['🌵'], 
    'mountains': ['⛰️'], 
    'sunrise, sunset': ['🌄','🌅'], 
    'moon': ['🌙'], 
    'rain': ['🌧️', '🌈'], 
    'food, groceries': ['🍔', '🥘', '🍕'], 
    'beer, wine, alcohol, drinking': ['🍺', '🍷', '🍾'], 
    'pingpong': ['🏓'], 
    'launch, rocket, beginning': ['🚀'], 
    'car, driving': ['🚙'], 
    'art': ['🎨'], 
    'music': ['🎹', '🎸', '🎧'], 
    'flight, airplane, travel': ['✈️'], 
    'work, tools, building': ['🔨', '🛠️'], 
    'new york': ['🗽'], 
    'science': ['🔭🔬'], 
    'shower': ['🚿'], 
    'technology, AI, computers': ['💻', '🤖']
}